storacha/specs

w3-account.md

Wrote a specification for explaining accounts and how they correlate with spaces

w3-accounts

---

.github/workflows/words-to-ignore.txt
w3-account.md

Minor edits to
- improve the readability of the spec
- fix typos and wordos
- fix nesting of headers
License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>

docs: readability edit of the w3-account spec

---

w3-account.md

Motivation:
* resolve https://github.com/web3-storage/specs/issues/29
* I asked @Gozala via slack and he confirmed that `./sign` was from old versions, and this is meant to be `./update` (defined above in doc)

fix typo of ./sign can that should be ./update

---

w3-account.md

- `./update` `iss` SHOULD match `with`
- `./update` `nb.key` MUST match access/authorize `with`
- fixes some links and improves some descriptions

fix: authorize/update definition

---

w3-access.md

Motivation:
* https://github.com/web3-storage/specs/issues/45
Note:
* this is backward incompatible, but afaict this protocol is pre-implementation, so I think that should be ok

feat!: access/delegate delegation set is at nb.delegations instead of nb root

---

w3-provider.md

The `consumer` field definition implied that it could be undefined or `did:*` or `did:key:zSpace` this PR makes it just either undefined for multiples spaces or `did:key:zSpace` for a specific space

fix: normalize provider/get and consumer/add consumer field

---

w3-store.md

sync with the work merged in https://github.com/web3-storage/w3protocol/pull/423

feat: update docs with new `pre` caveat for `store/list` and `upload/list`

---

Readme.md

I don't think we call this the .storage protocol anywhere, and it seems like it's idiomatic to call it the w3up protocol, so let's make it official?

update README with w3up name

---

.github/workflows/words-to-ignore.txt
Readme.md
w3-clock.md

This specification describes a method of managing a [Merkle Clock](https://arxiv.org/pdf/2004.00107.pdf) of partially ordered events via UCAN invocations.

feat: add merkle clock spec

---

w3-aggregation.md

Synced with @Gozala today and it makes sense that `aggregate/offer` resource would be `web3.storage`. We should at it like we use spaces within web3.storage system. Spade have multiple customers, each one with its own (out of band negotiated terms)  resource within Spade.
Note: Actually `aggregate/get` was already in this format.

fix: aggregate offer with should be w3s

---

w3-aggregation.md

Context https://github.com/web3-storage/w3up/pull/787#issuecomment-1579596427
cc @ribasushi

fix: align aggregation namings from commp learnings

---

w3-aggregation.md

Now we can simply rely on CIDs with encoded size/length instead of moving around size/height, so simplifying all the names we have also been using like `subject` and `pieceLink`

fix: aggregate spec can rely on piece cid with encoded size

---

.github/workflows/words-to-ignore.txt
w3-aggregation.md
w3-filecoin.md

Based on my previous proposal to @Gozala that @Gozala covered in https://github.com/web3-storage/RFC/pull/2
Changes the aggregation spec introducing new capabilities and a new role. Main reasoning for this change is the new distinction between Storefront and Aggregator (previously had same identity), where a Storefront (web3.storage, nftstorage)  will receive/compute Filecoin pieces (from received CAR files) and offer them to an Aggregator (w3filecoin). The aggregator's role is to put multiple pieces together to offer a large piece (aggregate) to a Broker (spade-proxy).
Per the above, the new invocations added are described in https://www.notion.so/2023-07-26-aggregation-protocol-contract-sign-and-report-API-12b4a7f0e92f4b789c331322e2629817
Renamed spec from aggregation to w3 filecoin …

feat: w3filecoin spec with storefront aggregator broker and chain roles

---

w3-filecoin.md

Per discussion in https://github.com/web3-storage/specs/pull/71#issuecomment-1670091520 , this PR separates capabilities of queue and enqueue into different ones, so that we can have guarantee that storefront requester are who they are by sending their DID in the `with` field, that can then be used in the `nb` field for the dequeue.

fix: w3filecoin spec separate capabilities to queue and dequeue

---

w3-admin.md

I think these deserve their own spec (and that we could potentially fold the rate-limits spec into this one) since they all act against the service resource itself.

feat: add documentation for w3admin related capabilities

---

.github/workflows/words-to-ignore.txt
w3-admin.md

At a high level, these are designed to enable administrators like @dchoi27 to figure out which space a given CID is associated with.
Problem CIDs come to us from a variety of sources - sometimes they are content CIDs that correspond to a particular `upload/add` invocation and sometimes they are "shard" CIDs that identify one of the CARs stored using `store/add` that make up the shards of a larger upload. `admin/upload/inspect` returns information about the upload and `admin/store/inspect` returns information about particular shards, so given an unknown CID administrators should check both.

feat: propose `admin/upload/inspect` and `admin/store/inspect` capabilities

---

w3-filecoin.md

Fixes aggregate/accept receipt:
1. inclusion proof was wrongly here. It should only be in `piece/accept` because it is piece specific proof within an aggregate
2. added `aggregate` in receipt to be coherent with other receipts for `*/accept`
Fixes filecoin/accept receipt:
1. added `piece` and `aggregate` in receipt to be coherent with other receipts for `*/accept`
2. swaped `aux` to be a property per https://github.com/web3-storage/w3up/pull/974#discussion_r1368342534

fix: filecoin spec aggregate accept receipt type

---

w3-store.md

These capabilities are intended for checking inclusion, or getting the additional properties we store. This will allow clients to verify all the shards for an upload have been removed before removing an upload.
```js
{
can: "store/get",
with: "did:key:abc...",
nb: {
link: "bag...",
}
}
```
Error if `link` shard cid is not in space or...
```ts
interface StoreListItem {
/** CID of the stored CAR. */
link: string
/** Size in bytes of the stored CAR */
size: number
/** Link to a related CAR, used for sharded uploads */
origin?: string,
/** ISO-8601 timestamp when CAR was added to the space */
insertedAt: string,
}
```
```js
{
can: "upload/get",
with: "did:key:abc...",
nb: {
root: "bafyabc..."
}
}
```
`Error` if root is not in uploads for space or...
```ts
interface UploadListItem {
/** Root …
```

feat: add `store/get` & `upload/get` capabilities

---

w3-filecoin.md

Adds previously implemented `filecoin/info` capability. Also changes spec state to reflect current state

fix: add filecoin info capability

---

w3-space.md

Adds basic space spec. While at first considered to add it to `w3-account` or `w3-access`, I realized that account has a specific focus on high level account with multiple spaces, while access focus on "aggregating and managing delegated capabilities across agents". Therefore, ended up with new spec document to reflect the basics of a space protocol.
It is complemented by `w3-account` and `w3-provider` on how to integrate account and providers, while in its basic form adds wire protocol for the space specific capabilities that do not fall under the umbrella of `account` and `provider`.

docs: add w3 space basic spec

---

.github/workflows/words-to-ignore.txt
w3-session.md

Motivation:
* help people who want to dive into implementation details find the relevant reference implementations

link to implementations of w3-session.md

---

w3-filecoin.md

Rationale
* helps to understand protocol vs reality to see an impl
* i'm trying to ensure there are impl links for all [stable specs](https://github.com/web3-storage/specs#stable-specs), and this is one of them atm

add implementation links for w3-filecoin

---

.github/workflows/words-to-ignore.txt
did-mailto.md

Import did:mailto spec locally so we don't have to link to https://github.com/ucan-wg/did-mailto/pull/2 in ucan-wg

chore: import did:mailto spec

---

.github/workflows/words-to-ignore.txt
w3-account.md
w3-ucan-bridge.md

To support users in languages that do not have existing UCAN invocation implementations, we are going to launch a bridge that allows them to make simple HTTP requests with JSON bodies that we transform into proper UCAN invocations.

feat: add specification for UCAN HTTP bridge

---

.github/workflows/words-to-ignore.txt
w3-store.md

Updates store and upload specs so they are more like other specs as opposed to been more like documentation.

feat: revamp store & upload specs

---

.github/workflows/words-to-ignore.txt
w3-blob.md
w3-ucan.md

Amend spec per agreements last Thursday, few notes:
1. I end up describing `ucan/conclude` capability as opposed to `ucan/receipt`, although we could go with receipt route if it is more preferred. Either one will likely differ from where spec will end up, but current version is likely to be closer than version with `ucan/receipt`.
2. `await/ok` in the `out` field may change slightly as we're discussing doing something like `{ 'ucan/await': ['.ok.claim', { "/": ... }] }` so you could drill down deeper, however there is no agreement in UCAN WG on exact schema yet.

feat: introduce http/put capability

---

.github/workflows/words-to-ignore.txt
w3-blob.md

[Preview](https://github.com/web3-storage/specs/blob/fix/align-blob-with-impl/w3-blob.md)

chore: switch to more coherent naming

---

w3-blob.md

This PR adds blob listing and removing to the spec as a first version. It is clear we will want to improve this later on, but we agreed in shipping this doing same behaviour as `store/list` and `store/remove` so that we do not lose functionality by shipping blob protocol by default.
With the above in mind, and as we agreed this PR basically ports the `store/list` and `store/remove` here, with some adaptions to be consistent with structure in this document, as well as usage of `ts` code snippets instead of `ipldsch` to also be consistent

feat: add blob list and remove into spec

---

.github/workflows/words-to-ignore.txt
w3-index.md

[📽️ Preview](https://github.com/web3-storage/specs/blob/feat/w3-index/w3-index.md)
This is a draft of proposed content index publishing spec spawn off of https://github.com/web3-storage/RFC/blob/main/rfc/ipni-w3c.md RFC from @gammazero

feat: w3 index spec

---

w3-blob.md

Adds the `blob/get` capability spec which is analogous to https://github.com/w3s-project/specs/pull/82

feat: add blob/get

---

w3-provider.md

This PR reverts #107 
Why? The spec currently diverges wildly from the implementation, and there are no immediate plans to implement the revised version.
We can absolutely return to this once we have immediate plans for implementation. Generally, the specs should match exactly the implementation, or there should be notes as to why.
I don't know the history and rationale for the revamp, but for now, it's a huge source of confusion.

Revert provider revamp

---

did-mailto.md
w3-access.md
w3-account.md
w3-blob.md
w3-filecoin.md
w3-index.md
w3-provider.md
w3-session.md
w3-store.md

This PR updates the blob spec to use UCAN 0.9 parlance - the version implemented and used in production.
[📖 Preview](https://github.com/storacha/specs/blob/fix/blob-spec-ucan-09-parlance/w3-blob.md)

fix: blob spec in UCAN 0.9 parlance

---

.github/workflows/lint.yml
w3-store.md

Update the success responses for the different upload capabilities so that they align with the implementation in `upload-service`: https://github.com/storacha/upload-service/blob/104fe31965e0071ab2f36f2426289030bcea6288/packages/capabilities/src/types.ts#L737-L751

fix: align spec of upload capabilities with the current implementation

---

.github/workflows/words-to-ignore.txt
w3-replication.md

Based on: https://github.com/storacha/RFC/pull/45
Formalizes the protocol providing invocation and receipt schemas.
There are a few differences from the RFC:
1. `space/blob/replicate` receipt:
* Includes async tasks and receipts for `blob/allocate` in additon to `blob/transfer`.
* Successful output includes `site: [{ "ucan/await": [".out.ok.site", Link<TransferReplicaBlob>] }]` for obtaining the location commitments for each of the replicated blobs.
2. `blob/replica/transfer` invocation includes the space DID.
3. We use `site` for field name of location claim instead of `location` for consistency with blob protocol.
[📚 Preview](https://github.com/storacha/specs/blob/feat/add-replication-protocol/w3-replication.md)

feat: replication protocol

---

w3-replication.md

Rework `space/blob/replicate` to count the original copy in the number of replicas, and reword things to align with that.
Most notably, I've changed "Primary Node" to "Source Node" and emphasized that it's not a property intrinsic to the node, but a description of its role in the replication operation. Curious how that looks to other folks.

feat: `replicas` includes the original copy
